# Generated by Django 2.2.3 on 2019-07-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=20)),
                ('open_id', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
    ]
