# Generated by Django 2.2.3 on 2019-07-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_numer',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
