# Generated by Django 2.2.3 on 2019-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190723_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatarUrl',
            field=models.CharField(blank=True, default='img/avatar/default.jpg', max_length=256),
        ),
    ]
