# Generated by Django 2.2.3 on 2019-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_avatarurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=40),
        ),
    ]
