# Generated by Django 2.2.3 on 2019-07-25 07:35

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190723_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_detail', models.TextField(blank=True)),
                ('image', models.ImageField(default='img/post/example/1.jpg', max_length=256, upload_to=news.models.post_image_path)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
            options={
                'ordering': ['post_time'],
            },
        ),
        migrations.CreateModel(
            name='PostLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Post')),
            ],
        ),
    ]
